### ISSUE TITLE
For data collected with Gazepoint, make sure event detection (and all scripts thus far except DataQuality.py), is using "Time" column (colum AW) and NOT MissionTime

### ISSUE THREAD

**Issue by sdevlin3001** [Clemson-Riggs-Lab/Eye_Tracking_S20#23]
This is a random issue I am just realizing could be problematic when analyzing all eye tracking files at once. For data collected with Gazepoint, make sure all scripts (except DataQuality.py), is using "Time" column (column AW) and **NOT** MissionTime. This is because MissionTime is only established once running DataQuality.py, which I will most likely run for all/most files at some point, BUT on the chance I don't, I want to make sure event detection scripts can be executed smoothly. From what I can tell, ED_with_pandas.py is the only file using MissionTime for Gazepoint eye trackers, all other files are, correctly, using the "Time" column (column AW), so this is currently only a minor issue, but I wanted to post it to general issues for awareness. @samsmith0704 if you could confirm that it is only an issue for ED_with_pandas.py, that would be great.

**Comment by bluepaint723** [comment]
Hey Shannon. Just to be clear, you want me to take times from gazepoint
data from the 'Time' column (doing so would make the code identical for
FOVIO and gazepoint).

- Sam

**Comment by sdevlin3001** [comment]
Hi Sam. It technically won't be identical to FOVIO because FOVIO's Time column is in units of ms and Gazepoint's time units are in seconds. Angular velocity values should not be impacted since they should already be in units of degrees/second but I imagine start and end times of the saccade will be. Does that make sense?
